IOC_TOP = /reg/g/pcds/epics/ioc/common/ads-ioc/R0.2.4
IOC_INSTANCE_PATH := $(shell pwd)

PROJECT_NAME = plc_kfe_xgmd_vac
PROJECT_PATH := ../../plc-kfe-xgmd-vac/plc_kfe_xgmd_vac.tsproj
PLC = plc_kfe_xgmd_vac

PYTMC_OPTS = 
PREFIX = IOC:PLC:KFE:XGMD:VAC

PRODUCTION_IOC := 1

include $(IOC_TOP)/iocBoot/templates/Makefile.base
