IOC_TOP = /reg/g/pcds/epics/ioc/common/ads-ioc/R0.8.0
IOC_INSTANCE_PATH := $(shell pwd)

PROJECT_NAME = plc_kfe_xgmd_vac
PROJECT_PATH := ../../plc-kfe-xgmd-vac/plc_kfe_xgmd_vac.tsproj
PLC = plc_kfe_xgmd_vac_sim

PYTMC_OPTS = 
PREFIX = PREFIX:

include $(IOC_TOP)/iocBoot/templates/Makefile.base
