<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="F_HV_ILK" Id="{93ea2e20-5fc5-4962-9409-abe8b95bf005}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_HV_ILK : BOOL
VAR_INPUT
	IG	:	ST_VG; // Gauge used for interlocking the high voltage supply 
	HV	:	ST_HV; // Structure representing HV control
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_HV_ILK := ((IG.xPRESS_OK = TRUE)
			AND (IG.rPRESS < HV.rPRO_SP));]]></ST>
    </Implementation>
    <LineIds Name="F_HV_ILK">
      <LineId Id="7" Count="0" />
      <LineId Id="13" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>