<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="F_TURBO_PROT_SLND_ILK" Id="{2cd3cb76-73f3-4300-a3c4-dd435cd2a0c0}" SpecialFunc="None">
    <Declaration><![CDATA[(*
	Interlock function for solenoid valve located behind the central turbo pump. 
*)
FUNCTION F_TURBO_PROT_SLND_ILK : BOOL
VAR_INPUT
    i_Turbo : ST_PTM; // Turbo Pump
	i_stISG : ST_VG; //Gauge measuring inlet Pressure e.g Pirani
	i_stBSG : ST_VG; //Gauge measuring backing Pressure e.g Pirani
	ScrollPump : ST_RoughPump; // Roughing pump
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_TURBO_PROT_SLND_ILK := (i_stISG.xPRESS_OK AND i_stISG.rPRESS < i_Turbo.rInletPressureSP)
						    AND (i_stBSG.xPRESS_OK AND i_stBSG.rPRESS < i_Turbo.rBackingPressureSP)
                            AND (ScrollPump.eState = pumpRUNNING);]]></ST>
    </Implementation>
    <LineIds Name="F_TURBO_PROT_SLND_ILK">
      <LineId Id="20" Count="1" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>